name: Debug Environment Variables

on:
  workflow_dispatch: # Trigger this workflow manually

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set environment variables
      - name: Set Environment Variables
        env:
          ENV_DATASOURCE_URL: ${{ myenv.ENV_DATASOURCE_URL }}
          ENV_DATASOURCE_USERNAME: ${{ myenv.ENV_DATASOURCE_USERNAME }}
          ENV_DATASOURCE_PASSWORD: ${{ myenv.ENV_DATASOURCE_PASSWORD }}
          JWT_SECRETKEY: ${{ myenv.JWT_SECRETKEY }}
        run: |
          echo "Printing Environment Variables:"
          echo "ENV_DATASOURCE_URL: $ENV_DATASOURCE_URL"
          echo "ENV_DATASOURCE_USERNAME: $ENV_DATASOURCE_USERNAME"
          echo "ENV_DATASOURCE_PASSWORD: $ENV_DATASOURCE_PASSWORD"
          echo "JWT_SECRETKEY: $JWT_SECRETKEY"