# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alpha-olsp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2ff01ee21d494d488185c111f6a110ba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_73bd52ebac9b452b95160b1d1b96b68d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2ff01ee21d494d488185c111f6a110ba }}/hhzneo/alpha-olsp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alpha-olsp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d21f3335a9e14d718e1a2cbfa263a218 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2ff01ee21d494d488185c111f6a110ba }}/hhzneo/alpha-olsp:${{ github.sha }}'